### ISSUE TITLE
open floating window throws error

### ISSUE THREAD

**Issue by qvieth** [wfxr/minimap.vim#155] opened 2022-05-06 03:03 UTC
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS: Fedora 35
 
## Version info

NVIM v0.8.0-dev+112-g13520aae1

## Question / Problem and steps to reproduce
open packer floating window or any floating window(in my case it was toggleterm & rnvimr) cause this issue

![image](https://user-images.githubusercontent.com/71810726/167059687-1baddcac-9103-46f7-969e-5de49c80853d.png)

**Comment by ZNielsen** [comment] 2022-05-09 16:42
Looks like a dupe of #153

**Comment by ZNielsen** [comment] 2022-05-11 16:31
Do you mind testing this fix on branch `GH-153_test_fix` when you get a chance? If you are using a plugin manager, there's usually an option for which branch to use (requires an update/upgrade/pull/ect.)

Example for Plugged:

```
Plug 'wfxr/minimap.vim', {'branch': 'GH-153_test_fix'}
```

**Comment by qvieth** [comment] 2022-05-12 01:16
I used the `GH-153_test_fix` branch and unfortunately still can see the issue

![image](https://user-images.githubusercontent.com/71810726/167972555-270c6a1a-5425-40d4-a288-430dcbde8b9d.png)

**Closed** 2023-10-02 20:02 UTC
Labels: bug
